# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  - id: trailing-whitespace
    exclude: ^(docs/(index|migration).md|.github/workflows/publish.yml|mkdocs_blogging_plugin/(templates/blog.html|util.py))
  - id: end-of-file-fixer
    exclude: ^(.gitignore|docs/theme.md|MANIFEST.in|mkdocs.yml|mkdocs_blogging_plugin/(templates/blog.*.html|util.py)|requirements(-docs)?.txt)
  - id: check-yaml
  - id: check-added-large-files
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.2.0
  hooks:
  - id: pretty-format-toml
    args: [--autofix]
  - id: pretty-format-yaml
    args: [--autofix]
    exclude: ^(.github/workflows/publish.yml|mkdocs.yml)
- repo: https://github.com/commitizen-tools/commitizen
  rev: v2.20.3
  hooks:
  - id: commitizen
    stages: [commit-msg]
- repo: https://github.com/akaihola/darker
  rev: github-action-v1.3.2-2
  hooks:
  - id: darker
- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
  - id: isort
    name: isort (python)
